In [12]:
import numpy as np
import pandas as pd
import sys,time,json
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.model_selection import StratifiedKFold,GroupKFold,GridSearchCV,StratifiedGroupKFold, RandomizedSearchCV
from sklearn.utils import shuffle
from xgboost import XGBClassifier
from scipy.stats import randint
pd.set_option('display.max_columns', None)

In [13]:
subject_info_raw = pd.read_csv('/Users/eric/repos/aud/data/subject_info.csv')
subject_info = subject_info_raw.query("responsiveness>=0.25").copy(deep=True)
print(subject_info.shape)
subject_info.head()

(148, 5)

,subid,mema_count,last_morning_ema_day,first_morning_ema_day,responsiveness
0,1,64,89,0,0.711111
1,2,77,84,0,0.905882
2,3,87,89,0,0.966667
3,5,90,91,0,0.988889
4,6,79,86,0,0.908046

In [14]:
labels = pd.read_csv('/Users/eric/repos/aud/data/ml_labels_full_width.csv')
labels.head()

,subid,day,day_of_week_num_0,day_of_week_num_1,day_of_week_num_2,day_of_week_num_3,day_of_week_num_4,day_of_week_num_5,day_of_week_num_6,latest_ema_2,latest_ema_3,latest_ema_4,latest_ema_5,latest_ema_6,latest_ema_7,latest_ema_8,latest_ema_9,latest_ema_10,srm_ema_2,srm_ema_3,srm_ema_4,srm_ema_5,srm_ema_6,srm_ema_7,srm_ema_8,srm_ema_9,srm_ema_10,lrm_ema_2,lrm_ema_3,lrm_ema_4,lrm_ema_5,lrm_ema_6,lrm_ema_7,lrm_ema_8,lrm_ema_9,lrm_ema_10,recent_lapse_1,recent_lapse_3,recent_lapse_5,lapse_w0,lapse_w1,lapse_w3,lapse_w7,train_width
0,1,0,0,0,0,1,0,0,0,0.333333,1.000000,1.000000,0.666667,0.5,0.7,0.4,0.4,0.3,0.333333,1.000000,1.000000,0.666667,0.500000,0.700000,0.400000,0.4,0.3,0.333333,1.000000,1.000000,0.666667,0.50,0.700000,0.400000,0.400,0.3,False,False,False,0,0.0,0.0,0.0,90
1,1,1,0,0,0,0,1,0,0,0.166667,0.333333,0.333333,0.666667,0.5,0.2,0.4,0.6,0.3,0.250000,0.666667,0.666667,0.666667,0.500000,0.450000,0.400000,0.5,0.3,0.250000,0.666667,0.666667,0.666667,0.50,0.450000,0.400000,0.500,0.3,False,False,False,0,0.0,0.0,0.0,90
2,1,2,0,0,0,0,0,1,0,0.166667,0.333333,0.333333,0.666667,0.5,0.2,0.4,0.6,0.3,0.250000,0.666667,0.666667,0.666667,0.500000,0.450000,0.400000,0.5,0.3,0.250000,0.666667,0.666667,0.666667,0.50,0.450000,0.400000,0.500,0.3,False,False,False,0,0.0,0.0,0.0,90
3,1,3,0,0,0,0,0,0,1,0.166667,0.000000,0.000000,0.416667,0.5,0.2,0.3,0.5,0.3,0.222222,0.444444,0.444444,0.583333,0.500000,0.366667,0.366667,0.5,0.3,0.222222,0.444444,0.444444,0.583333,0.50,0.366667,0.366667,0.500,0.3,False,False,False,0,0.0,0.0,0.0,90
4,1,4,1,0,0,0,0,0,0,0.166667,0.083333,0.333333,0.666667,0.7,0.7,0.6,0.4,0.3,0.166667,0.138889,0.222222,0.583333,0.566667,0.366667,0.433333,0.5,0.3,0.208333,0.354167,0.416667,0.604167,0.55,0.450000,0.425000,0.475,0.3,False,False,False,0,0.0,0.0,0.0,90

In [15]:
ref = labels[['subid','day','lapse_w0']]
ref.rename(mapper={"lapse_w0":"lapse"},inplace=True,axis=1)
print("Overall lapse fraction", np.sum(ref.lapse)/ref.shape[0])
ref.head()

Overall lapse fraction 0.07548520521794463

/var/folders/yv/fz_ldjls7497yzp899r2yzw80000gn/T/ipykernel_6746/664960605.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  ref.rename(mapper={"lapse_w0":"lapse"},inplace=True,axis=1)

   subid  day  lapse
0      1    0      0
1      1    1      0
2      1    2      0
3      1    3      0
4      1    4      0

In [17]:
# Multi-fold testing
# Desired number of folds per repeat
splits=5
# Desired random states for each repeat
#random_states = [1]
random_states = [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15]

# Dictionaries for storing information
fold_dict = {}
ssm_dict = {}

# Get relevant X/Y/group information
X = ref[['subid','day']]
Y = ref[['lapse']]
groups = ref.subid

# Loop over the random states (i.e. loop over repeats)
for random_state in random_states:
    print("Random state: {}".format(random_state))
    # Set up sklearn object for generating folds
    sgkf = StratifiedGroupKFold(n_splits=splits,shuffle=True,random_state=random_state)
    test_list = []
    
    # Iterate over the train/test splits within this repeat
    for i,(train_index,test_index) in enumerate(sgkf.split(X,Y,groups=groups)):
        # Gather information about this split
        train_count = len(train_index)
        test_count = len(test_index)
        train_lapse = np.sum(Y.loc[train_index,"lapse"])
        train_prop = train_lapse/train_count
        test_lapse = np.sum(Y.loc[test_index,"lapse"])
        test_prop = test_lapse/test_count
        # Display split properties
        print("Fold {}, train count {}, test count {}, train_lapse {}, train lapse prop. {:.3f}, test_lapse {}, test lapse prop. {:.3f}"\
            .format(i,train_count,test_count,train_lapse,train_prop,test_lapse,test_prop))
        
        # Get subids included in train/test splits
        test_subids_iter = X.loc[test_index].subid.unique()
        train_subids_iter = X.loc[train_index].subid.unique()
        # Print the exact subject split info
        #print(test_subids_iter.tolist(),len(test_subids_iter))

        # Sanity checking that subids don't appear more than once
        if any([val in test_list for val in test_subids_iter]):
            print("error!")
            break
        else:
            test_list.extend(test_subids_iter.tolist())

        # Record information about the split
        fold_id = "split{}_rs{}_fold{}_id0".format(str(splits),str(random_state),str(i))
        fold_dict[fold_id]={'train':train_subids_iter.tolist(),'test':test_subids_iter.tolist(),'train_lapse_prop':train_prop,'test_lapse_prop':test_prop,'fold':i,'random_state':random_state}

        for id in test_subids_iter:
            ssm_key = "split{}_rs{}_fold{}_id{}".format(str(splits),str(random_state),str(i),str(id))
            ssm_dict[ssm_key] = {'train':train_subids_iter.tolist(),'test':int(id),'train_lapse_prop':train_prop,'test_lapse_prop':test_prop,'fold':i,'random_state':random_state}

ml_json = json.dumps(fold_dict, indent=4)
#print(ml_json)
with open('ml_fold_reference.json','w') as f:
    json.dump(fold_dict,indent=4,fp=f)

ssm_json = json.dumps(ssm_dict, indent=4)
#print(ssm_json)
with open('/Users/eric/repos/aud/data/ssm_fold_reference.json','w') as f:
    json.dump(ssm_dict,indent=4,fp=f)

# ML writing
ml_path = 'subid_ml_list_data_eff.txt'
f = open(ml_path,'w')
f.close()
f = open(ml_path,'a')
key_list = list(fold_dict.keys())
for key in key_list:
    if(key==key_list[-1]):
        f.write(key)
    else:
        f.write("{}\n".format(key))
f.close()

# SSM writing
ssm_path = '/Users/eric/repos/aud/chtc/subid_list_data_eff.txt'
f = open(ssm_path,'w')
f.close()
f = open(ssm_path,'a')
key_list = list(ssm_dict.keys())
for key in key_list:
    if(key==key_list[-1]):
        f.write("{} {}".format(key,'MAP_mle'))
    else:
        f.write("{} {}\n".format(key,'MAP_mle'))
f.close()

Random state: 1
Fold 0, train count 9940, test count 2632, train_lapse 817, train lapse prop. 0.082, test_lapse 132, test lapse prop. 0.050
Fold 1, train count 10089, test count 2483, train_lapse 737, train lapse prop. 0.073, test_lapse 212, test lapse prop. 0.085
Fold 2, train count 9833, test count 2739, train_lapse 743, train lapse prop. 0.076, test_lapse 206, test lapse prop. 0.075
Fold 3, train count 10283, test count 2289, train_lapse 761, train lapse prop. 0.074, test_lapse 188, test lapse prop. 0.082
Fold 4, train count 10143, test count 2429, train_lapse 738, train lapse prop. 0.073, test_lapse 211, test lapse prop. 0.087
Random state: 2
Fold 0, train count 9853, test count 2719, train_lapse 794, train lapse prop. 0.081, test_lapse 155, test lapse prop. 0.057
Fold 1, train count 10119, test count 2453, train_lapse 787, train lapse prop. 0.078, test_lapse 162, test lapse prop. 0.066
Fold 2, train count 10126, test count 2446, train_lapse 740, train lapse prop. 0.073, test_lapse 209, test lapse prop. 0.085
Fold 3, train count 10097, test count 2475, train_lapse 722, train lapse prop. 0.072, test_lapse 227, test lapse prop. 0.092
Fold 4, train count 10093, test count 2479, train_lapse 753, train lapse prop. 0.075, test_lapse 196, test lapse prop. 0.079
Random state: 3
Fold 0, train count 10241, test count 2331, train_lapse 784, train lapse prop. 0.077, test_lapse 165, test lapse prop. 0.071
Fold 1, train count 9980, test count 2592, train_lapse 777, train lapse prop. 0.078, test_lapse 172, test lapse prop. 0.066
Fold 2, train count 10017, test count 2555, train_lapse 753, train lapse prop. 0.075, test_lapse 196, test lapse prop. 0.077
Fold 3, train count 10000, test count 2572, train_lapse 728, train lapse prop. 0.073, test_lapse 221, test lapse prop. 0.086
Fold 4, train count 10050, test count 2522, train_lapse 754, train lapse prop. 0.075, test_lapse 195, test lapse prop. 0.077
Random state: 4
Fold 0, train count 10172, test count 2400, train_lapse 740, train lapse prop. 0.073, test_lapse 209, test lapse prop. 0.087
Fold 1, train count 9819, test count 2753, train_lapse 750, train lapse prop. 0.076, test_lapse 199, test lapse prop. 0.072
Fold 2, train count 10132, test count 2440, train_lapse 723, train lapse prop. 0.071, test_lapse 226, test lapse prop. 0.093
Fold 3, train count 10059, test count 2513, train_lapse 737, train lapse prop. 0.073, test_lapse 212, test lapse prop. 0.084
Fold 4, train count 10106, test count 2466, train_lapse 846, train lapse prop. 0.084, test_lapse 103, test lapse prop. 0.042
Random state: 5
Fold 0, train count 10001, test count 2571, train_lapse 733, train lapse prop. 0.073, test_lapse 216, test lapse prop. 0.084
Fold 1, train count 10103, test count 2469, train_lapse 769, train lapse prop. 0.076, test_lapse 180, test lapse prop. 0.073
Fold 2, train count 10099, test count 2473, train_lapse 743, train lapse prop. 0.074, test_lapse 206, test lapse prop. 0.083
Fold 3, train count 10153, test count 2419, train_lapse 838, train lapse prop. 0.083, test_lapse 111, test lapse prop. 0.046
Fold 4, train count 9932, test count 2640, train_lapse 713, train lapse prop. 0.072, test_lapse 236, test lapse prop. 0.089
Random state: 6
Fold 0, train count 9973, test count 2599, train_lapse 670, train lapse prop. 0.067, test_lapse 279, test lapse prop. 0.107
Fold 1, train count 9908, test count 2664, train_lapse 831, train lapse prop. 0.084, test_lapse 118, test lapse prop. 0.044
Fold 2, train count 10193, test count 2379, train_lapse 770, train lapse prop. 0.076, test_lapse 179, test lapse prop. 0.075
Fold 3, train count 10013, test count 2559, train_lapse 786, train lapse prop. 0.078, test_lapse 163, test lapse prop. 0.064
Fold 4, train count 10201, test count 2371, train_lapse 739, train lapse prop. 0.072, test_lapse 210, test lapse prop. 0.089
Random state: 7
Fold 0, train count 10237, test count 2335, train_lapse 780, train lapse prop. 0.076, test_lapse 169, test lapse prop. 0.072
Fold 1, train count 10169, test count 2403, train_lapse 812, train lapse prop. 0.080, test_lapse 137, test lapse prop. 0.057
Fold 2, train count 9992, test count 2580, train_lapse 739, train lapse prop. 0.074, test_lapse 210, test lapse prop. 0.081
Fold 3, train count 9890, test count 2682, train_lapse 743, train lapse prop. 0.075, test_lapse 206, test lapse prop. 0.077
Fold 4, train count 10000, test count 2572, train_lapse 722, train lapse prop. 0.072, test_lapse 227, test lapse prop. 0.088
Random state: 8
Fold 0, train count 10008, test count 2564, train_lapse 771, train lapse prop. 0.077, test_lapse 178, test lapse prop. 0.069
Fold 1, train count 10080, test count 2492, train_lapse 738, train lapse prop. 0.073, test_lapse 211, test lapse prop. 0.085
Fold 2, train count 10124, test count 2448, train_lapse 828, train lapse prop. 0.082, test_lapse 121, test lapse prop. 0.049
Fold 3, train count 10110, test count 2462, train_lapse 813, train lapse prop. 0.080, test_lapse 136, test lapse prop. 0.055
Fold 4, train count 9966, test count 2606, train_lapse 646, train lapse prop. 0.065, test_lapse 303, test lapse prop. 0.116
Random state: 9
Fold 0, train count 10004, test count 2568, train_lapse 751, train lapse prop. 0.075, test_lapse 198, test lapse prop. 0.077
Fold 1, train count 10093, test count 2479, train_lapse 716, train lapse prop. 0.071, test_lapse 233, test lapse prop. 0.094
Fold 2, train count 10159, test count 2413, train_lapse 749, train lapse prop. 0.074, test_lapse 200, test lapse prop. 0.083
Fold 3, train count 10080, test count 2492, train_lapse 746, train lapse prop. 0.074, test_lapse 203, test lapse prop. 0.081
Fold 4, train count 9952, test count 2620, train_lapse 834, train lapse prop. 0.084, test_lapse 115, test lapse prop. 0.044
Random state: 10
Fold 0, train count 10288, test count 2284, train_lapse 798, train lapse prop. 0.078, test_lapse 151, test lapse prop. 0.066
Fold 1, train count 10142, test count 2430, train_lapse 818, train lapse prop. 0.081, test_lapse 131, test lapse prop. 0.054
Fold 2, train count 10082, test count 2490, train_lapse 825, train lapse prop. 0.082, test_lapse 124, test lapse prop. 0.050
Fold 3, train count 9770, test count 2802, train_lapse 615, train lapse prop. 0.063, test_lapse 334, test lapse prop. 0.119
Fold 4, train count 10006, test count 2566, train_lapse 740, train lapse prop. 0.074, test_lapse 209, test lapse prop. 0.081
Random state: 11
Fold 0, train count 10157, test count 2415, train_lapse 793, train lapse prop. 0.078, test_lapse 156, test lapse prop. 0.065
Fold 1, train count 10053, test count 2519, train_lapse 785, train lapse prop. 0.078, test_lapse 164, test lapse prop. 0.065
Fold 2, train count 10047, test count 2525, train_lapse 786, train lapse prop. 0.078, test_lapse 163, test lapse prop. 0.065
Fold 3, train count 10019, test count 2553, train_lapse 751, train lapse prop. 0.075, test_lapse 198, test lapse prop. 0.078
Fold 4, train count 10012, test count 2560, train_lapse 681, train lapse prop. 0.068, test_lapse 268, test lapse prop. 0.105
Random state: 12
Fold 0, train count 9859, test count 2713, train_lapse 739, train lapse prop. 0.075, test_lapse 210, test lapse prop. 0.077
Fold 1, train count 9980, test count 2592, train_lapse 754, train lapse prop. 0.076, test_lapse 195, test lapse prop. 0.075
Fold 2, train count 10192, test count 2380, train_lapse 824, train lapse prop. 0.081, test_lapse 125, test lapse prop. 0.053
Fold 3, train count 10176, test count 2396, train_lapse 742, train lapse prop. 0.073, test_lapse 207, test lapse prop. 0.086
Fold 4, train count 10081, test count 2491, train_lapse 737, train lapse prop. 0.073, test_lapse 212, test lapse prop. 0.085
Random state: 13
Fold 0, train count 10190, test count 2382, train_lapse 810, train lapse prop. 0.079, test_lapse 139, test lapse prop. 0.058
Fold 1, train count 10028, test count 2544, train_lapse 680, train lapse prop. 0.068, test_lapse 269, test lapse prop. 0.106
Fold 2, train count 10133, test count 2439, train_lapse 750, train lapse prop. 0.074, test_lapse 199, test lapse prop. 0.082
Fold 3, train count 9835, test count 2737, train_lapse 787, train lapse prop. 0.080, test_lapse 162, test lapse prop. 0.059
Fold 4, train count 10102, test count 2470, train_lapse 769, train lapse prop. 0.076, test_lapse 180, test lapse prop. 0.073
Random state: 14
Fold 0, train count 10223, test count 2349, train_lapse 747, train lapse prop. 0.073, test_lapse 202, test lapse prop. 0.086
Fold 1, train count 9835, test count 2737, train_lapse 756, train lapse prop. 0.077, test_lapse 193, test lapse prop. 0.071
Fold 2, train count 9963, test count 2609, train_lapse 648, train lapse prop. 0.065, test_lapse 301, test lapse prop. 0.115
Fold 3, train count 10127, test count 2445, train_lapse 811, train lapse prop. 0.080, test_lapse 138, test lapse prop. 0.056
Fold 4, train count 10140, test count 2432, train_lapse 834, train lapse prop. 0.082, test_lapse 115, test lapse prop. 0.047
Random state: 15
Fold 0, train count 10148, test count 2424, train_lapse 705, train lapse prop. 0.069, test_lapse 244, test lapse prop. 0.101
Fold 1, train count 9933, test count 2639, train_lapse 770, train lapse prop. 0.078, test_lapse 179, test lapse prop. 0.068
Fold 2, train count 10008, test count 2564, train_lapse 725, train lapse prop. 0.072, test_lapse 224, test lapse prop. 0.087
Fold 3, train count 10045, test count 2527, train_lapse 770, train lapse prop. 0.077, test_lapse 179, test lapse prop. 0.071
Fold 4, train count 10154, test count 2418, train_lapse 826, train lapse prop. 0.081, test_lapse 123, test lapse prop. 0.051

In [5]:
splits=5
random_state=1
sgkf = StratifiedGroupKFold(n_splits=splits,shuffle=True,random_state=random_state)
X = ref[['subid','day']]
Y = ref[['lapse']]
groups = ref.subid
test_list = []
train_groups = {}
test_groups = {}
#fold_df_list = []
fold_dict = {}
ssm_dict = {}
#ssm_df_list = []
for i,(train_index,test_index) in enumerate(sgkf.split(X,Y,groups=groups)):
    train_count = len(train_index)
    test_count = len(test_index)
    train_lapse = np.sum(Y.loc[train_index,"lapse"])
    train_prop = train_lapse/train_count
    test_lapse = np.sum(Y.loc[test_index,"lapse"])
    test_prop = test_lapse/test_count
    print("Fold {}, train count {}, test count {}, train_lapse {}, train lapse prop. {:.3f}, test_lapse {}, test lapse prop. {:.3f}"\
          .format(i,train_count,test_count,train_lapse,train_prop,test_lapse,test_prop))
    #print(X.loc[train_index].subid.unique())
    test_subids_iter = X.loc[test_index].subid.unique()
    train_subids_iter = X.loc[train_index].subid.unique()
    print(test_subids_iter.tolist(),len(test_subids_iter))
    if any([val in test_list for val in test_subids_iter]):
        print("error!")
        break
    else:
        test_list.extend(test_subids_iter.tolist())
    test_groups[i]=test_subids_iter
    #print(test_subids_iter)
    train_groups[i]=train_subids_iter

    fold_id = "split{}_rs{}_fold{}_id0".format(str(splits),str(random_state),str(i))
    fold_dict[fold_id]={'train':train_subids_iter.tolist(),'test':test_subids_iter.tolist(),'train_lapse_prop':train_prop,'test_lapse_prop':test_prop,'fold':i,'random_state':random_state}

    for id in test_subids_iter:
        ssm_key = "split{}_rs{}_fold{}_id{}".format(str(splits),str(random_state),str(i),str(id))
        ssm_dict[ssm_key] = {'train':train_subids_iter.tolist(),'test':int(id),'train_lapse_prop':train_prop,'test_lapse_prop':test_prop,'fold':i,'random_state':random_state}

ml_json = json.dumps(fold_dict, indent=4)
print(ml_json)
with open('ml_fold_reference.json','w') as f:
    json.dump(fold_dict,indent=4,fp=f)

ssm_json = json.dumps(ssm_dict, indent=4)
print(ssm_json)
with open('/Users/eric/repos/aud/data/ssm_fold_reference.json','w') as f:
    json.dump(ssm_dict,indent=4,fp=f)

# ML writing
ml_path = 'subid_ml_list_data_eff.txt'
f = open(ml_path,'w')
f.close()
f = open(ml_path,'a')
key_list = list(fold_dict.keys())
for key in key_list:
    if(key==key_list[-1]):
        f.write(key)
    else:
        f.write("{}\n".format(key))
f.close()

# SSM writing
ssm_path = '/Users/eric/repos/aud/chtc/subid_list_data_eff.txt'
f = open(ssm_path,'w')
f.close()
f = open(ssm_path,'a')
key_list = list(ssm_dict.keys())
for key in key_list:
    if(key==key_list[-1]):
        f.write("{} {}".format(key,'MAP_mle'))
    else:
        f.write("{} {}\n".format(key,'MAP_mle'))
f.close()

Fold 0, train count 11194, test count 1378, train_lapse 831, train lapse prop. 0.074, test_lapse 118, test lapse prop. 0.086
[20, 28, 30, 33, 38, 44, 54, 58, 97, 109, 135, 188, 192, 200, 231, 241] 16
Fold 1, train count 11298, test count 1274, train_lapse 858, train lapse prop. 0.076, test_lapse 91, test lapse prop. 0.071
[15, 21, 31, 32, 43, 51, 63, 78, 84, 110, 116, 213, 214, 243, 262] 15
Fold 2, train count 11365, test count 1207, train_lapse 913, train lapse prop. 0.080, test_lapse 36, test lapse prop. 0.030
[18, 19, 34, 74, 76, 81, 118, 136, 156, 196, 215, 238, 240, 264] 14
Fold 3, train count 11258, test count 1314, train_lapse 893, train lapse prop. 0.079, test_lapse 56, test lapse prop. 0.043
[11, 29, 39, 88, 143, 149, 158, 163, 166, 169, 183, 203, 207, 222, 245] 15
Fold 4, train count 11442, test count 1130, train_lapse 828, train lapse prop. 0.072, test_lapse 121, test lapse prop. 0.107
[5, 6, 37, 48, 52, 64, 90, 92, 117, 172, 175, 189, 212, 223] 14
Fold 5, train count 11351, test count 1221, train_lapse 844, train lapse prop. 0.074, test_lapse 105, test lapse prop. 0.086
[2, 3, 9, 53, 77, 93, 94, 178, 187, 191, 211, 221, 234, 255, 265] 15
Fold 6, train count 11365, test count 1207, train_lapse 817, train lapse prop. 0.072, test_lapse 132, test lapse prop. 0.109
[1, 7, 10, 26, 27, 79, 86, 137, 167, 179, 180, 205, 218, 230] 14
Fold 7, train count 11300, test count 1272, train_lapse 823, train lapse prop. 0.073, test_lapse 126, test lapse prop. 0.099
[40, 59, 65, 82, 99, 121, 128, 130, 131, 185, 224, 225, 248, 252, 263] 15
Fold 8, train count 11280, test count 1292, train_lapse 812, train lapse prop. 0.072, test_lapse 137, test lapse prop. 0.106
[25, 42, 56, 66, 85, 98, 138, 150, 162, 171, 190, 208, 209, 236, 268] 15
Fold 9, train count 11295, test count 1277, train_lapse 922, train lapse prop. 0.082, test_lapse 27, test lapse prop. 0.021
[16, 23, 47, 100, 103, 119, 134, 139, 161, 181, 197, 201, 242, 259, 270] 15
{
    "split10_rs1_fold0_id0": {
        "train": [
            1,
            2,
            3,
            5,
            6,
            7,
            9,
            10,
            11,
            15,
            16,
            18,
            19,
            21,
            23,
            25,
            26,
            27,
            29,
            31,
            32,
            34,
            37,
            39,
            40,
            42,
            43,
            47,
            48,
            51,
            52,
            53,
            56,
            59,
            63,
            64,
            65,
            66,
            74,
            76,
            77,
            78,
            79,
            81,
            82,
            84,
            85,
            86,
            88,
            90,
            92,
            93,
            94,
            98,
            99,
            100,
            103,
            110,
            116,
            117,
            118,
            119,
            121,
            128,
            130,
            131,
            134,
            136,
            137,
            138,
            139,
            143,
            149,
            150,
            156,
            158,
            161,
            162,
            163,
            166,
            167,
            169,
            171,
            172,
            175,
            178,
            179,
            180,
            181,
            183,
            185,
            187,
            189,
            190,
            191,
            196,
            197,
            201,
            203,
            205,
            207,
            208,
            209,
            211,
            212,
            213,
            214,
            215,
            218,
            221,
            222,
            223,
            224,
            225,
            230,
            234,
            236,
            238,
            240,
            242,
            243,
            245,
            248,
            252,
            255,
            259,
            262,
            263,
            264,
            265,
            268,
            270
        ],
        "test": [
            20,
            28,
            30,
            33,
            38,
            44,
            54,
            58,
            97,
            109,
            135,
            188,
            192,
            200,
            231,
            241
        ],
        "train_lapse_prop": 0.07423619796319457,
        "test_lapse_prop": 0.08563134978229318,
        "fold": 0,
        "random_state": 1
    },
    "split10_rs1_fold1_id0": {
        "train": [
            1,
            2,
            3,
            5,
            6,
            7,
            9,
            10,
            11,
            16,
            18,
            19,
            20,
            23,
            25,
            26,
            27,
            28,
            29,
            30,
            33,
            34,
            37,
            38,
            39,
            40,
            42,
            44,
            47,
            48,
            52,
            53,
            54,
            56,
            58,
            59,
            64,
            65,
            66,
            74,
            76,
            77,
            79,
            81,
            82,
            85,
            86,
            88,
            90,
            92,
            93,
            94,
            97,
            98,
            99,
            100,
            103,
            109,
            117,
            118,
            119,
            121,
            128,
            130,
            131,
            134,
            135,
            136,
            137,
            138,
            139,
            143,
            149,
            150,
            156,
            158,
            161,
            162,
            163,
            166,
            167,
            169,
            171,
            172,
            175,
            178,
            179,
            180,
            181,
            183,
            185,
            187,
            188,
            189,
            190,
            191,
            192,
            196,
            197,
            200,
            201,
            203,
            205,
            207,
            208,
            209,
            211,
            212,
            215,
            218,
            221,
            222,
            223,
            224,
            225,
            230,
            231,
            234,
            236,
            238,
            240,
            241,
            242,
            245,
            248,
            252,
            255,
            259,
            263,
            264,
            265,
            268,
            270
        ],
        "test": [
            15,
            21,
            31,
            32,
            43,
            51,
            63,
            78,
            84,
            110,
            116,
            213,
            214,
            243,
            262
        ],
        "train_lapse_prop": 0.07594264471587892,
        "test_lapse_prop": 0.07142857142857142,
        "fold": 1,
        "random_state": 1
    },
    "split10_rs1_fold2_id0": {
        "train": [
            1,
            2,
            3,
            5,
            6,
            7,
            9,
            10,
            11,
            15,
            16,
            20,
            21,
            23,
            25,
            26,
            27,
            28,
            29,
            30,
            31,
            32,
            33,
            37,
            38,
            39,
            40,
            42,
            43,
            44,
            47,
            48,
            51,
            52,
            53,
            54,
            56,
            58,
            59,
            63,
            64,
            65,
            66,
            77,
            78,
            79,
            82,
            84,
            85,
            86,
            88,
            90,
            92,
            93,
            94,
            97,
            98,
            99,
            100,
            103,
            109,
            110,
            116,
            117,
            119,
            121,
            128,
            130,
            131,
            134,
            135,
            137,
            138,
            139,
            143,
            149,
            150,
            158,
            161,
            162,
            163,
            166,
            167,
            169,
            171,
            172,
            175,
            178,
            179,
            180,
            181,
            183,
            185,
            187,
            188,
            189,
            190,
            191,
            192,
            197,
            200,
            201,
            203,
            205,
            207,
            208,
            209,
            211,
            212,
            213,
            214,
            218,
            221,
            222,
            223,
            224,
            225,
            230,
            231,
            234,
            236,
            241,
            242,
            243,
            245,
            248,
            252,
            255,
            259,
            262,
            263,
            265,
            268,
            270
        ],
        "test": [
            18,
            19,
            34,
            74,
            76,
            81,
            118,
            136,
            156,
            196,
            215,
            238,
            240,
            264
        ],
        "train_lapse_prop": 0.08033435987681478,
        "test_lapse_prop": 0.029826014913007456,
        "fold": 2,
        "random_state": 1
    },
    "split10_rs1_fold3_id0": {
        "train": [
            1,
            2,
            3,
            5,
            6,
            7,
            9,
            10,
            15,
            16,
            18,
            19,
            20,
            21,
            23,
            25,
            26,
            27,
            28,
            30,
            31,
            32,
            33,
            34,
            37,
            38,
            40,
            42,
            43,
            44,
            47,
            48,
            51,
            52,
            53,
            54,
            56,
            58,
            59,
            63,
            64,
            65,
            66,
            74,
            76,
            77,
            78,
            79,
            81,
            82,
            84,
            85,
            86,
            90,
            92,
            93,
            94,
            97,
            98,
            99,
            100,
            103,
            109,
            110,
            116,
            117,
            118,
            119,
            121,
            128,
            130,
            131,
            134,
            135,
            136,
            137,
            138,
            139,
            150,
            156,
            161,
            162,
            167,
            171,
            172,
            175,
            178,
            179,
            180,
            181,
            185,
            187,
            188,
            189,
            190,
            191,
            192,
            196,
            197,
            200,
            201,
            205,
            208,
            209,
            211,
            212,
            213,
            214,
            215,
            218,
            221,
            223,
            224,
            225,
            230,
            231,
            234,
            236,
            238,
            240,
            241,
            242,
            243,
            248,
            252,
            255,
            259,
            262,
            263,
            264,
            265,
            268,
            270
        ],
        "test": [
            11,
            29,
            39,
            88,
            143,
            149,
            158,
            163,
            166,
            169,
            183,
            203,
            207,
            222,
            245
        ],
        "train_lapse_prop": 0.07932137146917748,
        "test_lapse_prop": 0.0426179604261796,
        "fold": 3,
        "random_state": 1
    },
    "split10_rs1_fold4_id0": {
        "train": [
            1,
            2,
            3,
            7,
            9,
            10,
            11,
            15,
            16,
            18,
            19,
            20,
            21,
            23,
            25,
            26,
            27,
            28,
            29,
            30,
            31,
            32,
            33,
            34,
            38,
            39,
            40,
            42,
            43,
            44,
            47,
            51,
            53,
            54,
            56,
            58,
            59,
            63,
            65,
            66,
            74,
            76,
            77,
            78,
            79,
            81,
            82,
            84,
            85,
            86,
            88,
            93,
            94,
            97,
            98,
            99,
            100,
            103,
            109,
            110,
            116,
            118,
            119,
            121,
            128,
            130,
            131,
            134,
            135,
            136,
            137,
            138,
            139,
            143,
            149,
            150,
            156,
            158,
            161,
            162,
            163,
            166,
            167,
            169,
            171,
            178,
            179,
            180,
            181,
            183,
            185,
            187,
            188,
            190,
            191,
            192,
            196,
            197,
            200,
            201,
            203,
            205,
            207,
            208,
            209,
            211,
            213,
            214,
            215,
            218,
            221,
            222,
            224,
            225,
            230,
            231,
            234,
            236,
            238,
            240,
            241,
            242,
            243,
            245,
            248,
            252,
            255,
            259,
            262,
            263,
            264,
            265,
            268,
            270
        ],
        "test": [
            5,
            6,
            37,
            48,
            52,
            64,
            90,
            92,
            117,
            172,
            175,
            189,
            212,
            223
        ],
        "train_lapse_prop": 0.0723649711588883,
        "test_lapse_prop": 0.10707964601769912,
        "fold": 4,
        "random_state": 1
    },
    "split10_rs1_fold5_id0": {
        "train": [
            1,
            5,
            6,
            7,
            10,
            11,
            15,
            16,
            18,
            19,
            20,
            21,
            23,
            25,
            26,
            27,
            28,
            29,
            30,
            31,
            32,
            33,
            34,
            37,
            38,
            39,
            40,
            42,
            43,
            44,
            47,
            48,
            51,
            52,
            54,
            56,
            58,
            59,
            63,
            64,
            65,
            66,
            74,
            76,
            78,
            79,
            81,
            82,
            84,
            85,
            86,
            88,
            90,
            92,
            97,
            98,
            99,
            100,
            103,
            109,
            110,
            116,
            117,
            118,
            119,
            121,
            128,
            130,
            131,
            134,
            135,
            136,
            137,
            138,
            139,
            143,
            149,
            150,
            156,
            158,
            161,
            162,
            163,
            166,
            167,
            169,
            171,
            172,
            175,
            179,
            180,
            181,
            183,
            185,
            188,
            189,
            190,
            192,
            196,
            197,
            200,
            201,
            203,
            205,
            207,
            208,
            209,
            212,
            213,
            214,
            215,
            218,
            222,
            223,
            224,
            225,
            230,
            231,
            236,
            238,
            240,
            241,
            242,
            243,
            245,
            248,
            252,
            259,
            262,
            263,
            264,
            268,
            270
        ],
        "test": [
            2,
            3,
            9,
            53,
            77,
            93,
            94,
            178,
            187,
            191,
            211,
            221,
            234,
            255,
            265
        ],
        "train_lapse_prop": 0.0743546824068364,
        "test_lapse_prop": 0.085995085995086,
        "fold": 5,
        "random_state": 1
    },
    "split10_rs1_fold6_id0": {
        "train": [
            2,
            3,
            5,
            6,
            9,
            11,
            15,
            16,
            18,
            19,
            20,
            21,
            23,
            25,
            28,
            29,
            30,
            31,
            32,
            33,
            34,
            37,
            38,
            39,
            40,
            42,
            43,
            44,
            47,
            48,
            51,
            52,
            53,
            54,
            56,
            58,
            59,
            63,
            64,
            65,
            66,
            74,
            76,
            77,
            78,
            81,
            82,
            84,
            85,
            88,
            90,
            92,
            93,
            94,
            97,
            98,
            99,
            100,
            103,
            109,
            110,
            116,
            117,
            118,
            119,
            121,
            128,
            130,
            131,
            134,
            135,
            136,
            138,
            139,
            143,
            149,
            150,
            156,
            158,
            161,
            162,
            163,
            166,
            169,
            171,
            172,
            175,
            178,
            181,
            183,
            185,
            187,
            188,
            189,
            190,
            191,
            192,
            196,
            197,
            200,
            201,
            203,
            207,
            208,
            209,
            211,
            212,
            213,
            214,
            215,
            221,
            222,
            223,
            224,
            225,

In [15]:
ref.shape

(12572, 3)

In [41]:
# LOO case

X = ref[['subid','day']]
Y = ref[['lapse']]

test_list = []
train_groups = {}
test_groups = {}

fold_dict = {}
ssm_dict = {}

included_subjects = np.unique(ref.subid)
for i, subject in enumerate(included_subjects):
    train_index = ref.query("subid!=@subject").index
    test_index = ref.query("subid==@subject").index
    train_count = len(train_index)
    test_count = len(test_index)
    train_lapse = np.sum(Y.loc[train_index,"lapse"])
    train_prop = train_lapse/train_count
    test_lapse = np.sum(Y.loc[test_index,"lapse"])
    test_prop = test_lapse/test_count
    print("Fold {}, train count {}, test count {}, train_lapse {}, train lapse prop. {:.3f}, test_lapse {}, test lapse prop. {:.3f}"\
          .format(i,train_count,test_count,train_lapse,train_prop,test_lapse,test_prop))
    test_subids_iter = X.loc[test_index].subid.unique()
    train_subids_iter = X.loc[train_index].subid.unique()
    print(test_subids_iter.tolist(),len(test_subids_iter))
    if any([val in test_list for val in test_subids_iter]):
        print("error!")
        break
    else:
        test_list.extend(test_subids_iter.tolist())
    test_groups[i]=test_subids_iter
    #print(test_subids_iter)
    train_groups[i]=train_subids_iter

    fold_id = "splitLOO0_rsLOO0_foldLOO0_id{}".format(str(subject))
    fold_dict[fold_id]={'train':train_subids_iter.tolist(),'test':test_subids_iter.tolist(),'train_lapse_prop':train_prop,'test_lapse_prop':test_prop,'fold':'LOO','random_state':'LOO'}
    ssm_dict[fold_id] = {'train':train_subids_iter.tolist(),'test':int(subject),'train_lapse_prop':train_prop,'test_lapse_prop':test_prop,'fold':'LOO','random_state':'LOO'}

ml_json = json.dumps(fold_dict, indent=4)
print(ml_json)
with open('ml_fold_reference.json','w') as f:
    json.dump(fold_dict,indent=4,fp=f)

ssm_json = json.dumps(ssm_dict, indent=4)
print(ssm_json)
with open('/Users/eric/repos/aud/data/ssm_fold_reference.json','w') as f:
    json.dump(ssm_dict,indent=4,fp=f)

# ML writing
ml_path = 'subid_ml_list_data_eff.txt'
f = open(ml_path,'w')
f.close()
f = open(ml_path,'a')
key_list = list(fold_dict.keys())
for key in key_list:
    if(key==key_list[-1]):
        f.write(key)
    else:
        f.write("{}\n".format(key))
f.close()

# SSM writing
ssm_path = '/Users/eric/repos/aud/chtc/subid_list_data_eff.txt'
f = open(ssm_path,'w')
f.close()
f = open(ssm_path,'a')
key_list = list(ssm_dict.keys())
for key in key_list:
    if(key==key_list[-1]):
        f.write("{} {}".format(key,'MAP_mle'))
    else:
        f.write("{} {}\n".format(key,'MAP_mle'))
f.close()

Fold 0, train count 12482, test count 90, train_lapse 949, train lapse prop. 0.076, test_lapse 0, test lapse prop. 0.000
[1] 1
Fold 1, train count 12487, test count 85, train_lapse 944, train lapse prop. 0.076, test_lapse 5, test lapse prop. 0.059
[2] 1
Fold 2, train count 12482, test count 90, train_lapse 940, train lapse prop. 0.075, test_lapse 9, test lapse prop. 0.100
[3] 1
Fold 3, train count 12482, test count 90, train_lapse 949, train lapse prop. 0.076, test_lapse 0, test lapse prop. 0.000
[5] 1
Fold 4, train count 12485, test count 87, train_lapse 949, train lapse prop. 0.076, test_lapse 0, test lapse prop. 0.000
[6] 1
Fold 5, train count 12482, test count 90, train_lapse 932, train lapse prop. 0.075, test_lapse 17, test lapse prop. 0.189
[7] 1
Fold 6, train count 12482, test count 90, train_lapse 947, train lapse prop. 0.076, test_lapse 2, test lapse prop. 0.022
[9] 1
Fold 7, train count 12483, test count 89, train_lapse 934, train lapse prop. 0.075, test_lapse 15, test lapse prop. 0.169
[10] 1
Fold 8, train count 12482, test count 90, train_lapse 941, train lapse prop. 0.075, test_lapse 8, test lapse prop. 0.089
[11] 1
Fold 9, train count 12483, test count 89, train_lapse 949, train lapse prop. 0.076, test_lapse 0, test lapse prop. 0.000
[15] 1
Fold 10, train count 12496, test count 76, train_lapse 939, train lapse prop. 0.075, test_lapse 10, test lapse prop. 0.132
[16] 1
Fold 11, train count 12482, test count 90, train_lapse 949, train lapse prop. 0.076, test_lapse 0, test lapse prop. 0.000
[18] 1
Fold 12, train count 12482, test count 90, train_lapse 947, train lapse prop. 0.076, test_lapse 2, test lapse prop. 0.022
[19] 1
Fold 13, train count 12483, test count 89, train_lapse 948, train lapse prop. 0.076, test_lapse 1, test lapse prop. 0.011
[20] 1
Fold 14, train count 12483, test count 89, train_lapse 949, train lapse prop. 0.076, test_lapse 0, test lapse prop. 0.000
[21] 1
Fold 15, train count 12482, test count 90, train_lapse 949, train lapse prop. 0.076, test_lapse 0, test lapse prop. 0.000
[23] 1
Fold 16, train count 12482, test count 90, train_lapse 929, train lapse prop. 0.074, test_lapse 20, test lapse prop. 0.222
[25] 1
Fold 17, train count 12483, test count 89, train_lapse 946, train lapse prop. 0.076, test_lapse 3, test lapse prop. 0.034
[26] 1
Fold 18, train count 12482, test count 90, train_lapse 945, train lapse prop. 0.076, test_lapse 4, test lapse prop. 0.044
[27] 1
Fold 19, train count 12482, test count 90, train_lapse 949, train lapse prop. 0.076, test_lapse 0, test lapse prop. 0.000
[28] 1
Fold 20, train count 12495, test count 77, train_lapse 949, train lapse prop. 0.076, test_lapse 0, test lapse prop. 0.000
[29] 1
Fold 21, train count 12482, test count 90, train_lapse 949, train lapse prop. 0.076, test_lapse 0, test lapse prop. 0.000
[30] 1
Fold 22, train count 12485, test count 87, train_lapse 949, train lapse prop. 0.076, test_lapse 0, test lapse prop. 0.000
[31] 1
Fold 23, train count 12482, test count 90, train_lapse 949, train lapse prop. 0.076, test_lapse 0, test lapse prop. 0.000
[32] 1
Fold 24, train count 12482, test count 90, train_lapse 942, train lapse prop. 0.075, test_lapse 7, test lapse prop. 0.078
[33] 1
Fold 25, train count 12487, test count 85, train_lapse 926, train lapse prop. 0.074, test_lapse 23, test lapse prop. 0.271
[34] 1
Fold 26, train count 12482, test count 90, train_lapse 914, train lapse prop. 0.073, test_lapse 35, test lapse prop. 0.389
[37] 1
Fold 27, train count 12483, test count 89, train_lapse 946, train lapse prop. 0.076, test_lapse 3, test lapse prop. 0.034
[38] 1
Fold 28, train count 12482, test count 90, train_lapse 938, train lapse prop. 0.075, test_lapse 11, test lapse prop. 0.122
[39] 1
Fold 29, train count 12482, test count 90, train_lapse 949, train lapse prop. 0.076, test_lapse 0, test lapse prop. 0.000
[40] 1
Fold 30, train count 12482, test count 90, train_lapse 929, train lapse prop. 0.074, test_lapse 20, test lapse prop. 0.222
[42] 1
Fold 31, train count 12484, test count 88, train_lapse 924, train lapse prop. 0.074, test_lapse 25, test lapse prop. 0.284
[43] 1
Fold 32, train count 12485, test count 87, train_lapse 949, train lapse prop. 0.076, test_lapse 0, test lapse prop. 0.000
[44] 1
Fold 33, train count 12538, test count 34, train_lapse 937, train lapse prop. 0.075, test_lapse 12, test lapse prop. 0.353
[47] 1
Fold 34, train count 12483, test count 89, train_lapse 909, train lapse prop. 0.073, test_lapse 40, test lapse prop. 0.449
[48] 1
Fold 35, train count 12482, test count 90, train_lapse 935, train lapse prop. 0.075, test_lapse 14, test lapse prop. 0.156
[51] 1
Fold 36, train count 12482, test count 90, train_lapse 945, train lapse prop. 0.076, test_lapse 4, test lapse prop. 0.044
[52] 1
Fold 37, train count 12482, test count 90, train_lapse 940, train lapse prop. 0.075, test_lapse 9, test lapse prop. 0.100
[53] 1
Fold 38, train count 12482, test count 90, train_lapse 921, train lapse prop. 0.074, test_lapse 28, test lapse prop. 0.311
[54] 1
Fold 39, train count 12483, test count 89, train_lapse 922, train lapse prop. 0.074, test_lapse 27, test lapse prop. 0.303
[56] 1
Fold 40, train count 12482, test count 90, train_lapse 906, train lapse prop. 0.073, test_lapse 43, test lapse prop. 0.478
[58] 1
Fold 41, train count 12502, test count 70, train_lapse 944, train lapse prop. 0.076, test_lapse 5, test lapse prop. 0.071
[59] 1
Fold 42, train count 12482, test count 90, train_lapse 948, train lapse prop. 0.076, test_lapse 1, test lapse prop. 0.011
[63] 1
Fold 43, train count 12483, test count 89, train_lapse 949, train lapse prop. 0.076, test_lapse 0, test lapse prop. 0.000
[64] 1
Fold 44, train count 12482, test count 90, train_lapse 947, train lapse prop. 0.076, test_lapse 2, test lapse prop. 0.022
[65] 1
Fold 45, train count 12485, test count 87, train_lapse 949, train lapse prop. 0.076, test_lapse 0, test lapse prop. 0.000
[66] 1
Fold 46, train count 12486, test count 86, train_lapse 949, train lapse prop. 0.076, test_lapse 0, test lapse prop. 0.000
[74] 1
Fold 47, train count 12524, test count 48, train_lapse 949, train lapse prop. 0.076, test_lapse 0, test lapse prop. 0.000
[76] 1
Fold 48, train count 12483, test count 89, train_lapse 943, train lapse prop. 0.076, test_lapse 6, test lapse prop. 0.067
[77] 1
Fold 49, train count 12508, test count 64, train_lapse 942, train lapse prop. 0.075, test_lapse 7, test lapse prop. 0.109
[78] 1
Fold 50, train count 12485, test count 87, train_lapse 947, train lapse prop. 0.076, test_lapse 2, test lapse prop. 0.023
[79] 1
Fold 51, train count 12482, test count 90, train_lapse 947, train lapse prop. 0.076, test_lapse 2, test lapse prop. 0.022
[81] 1
Fold 52, train count 12534, test count 38, train_lapse 948, train lapse prop. 0.076, test_lapse 1, test lapse prop. 0.026
[82] 1
Fold 53, train count 12482, test count 90, train_lapse 948, train lapse prop. 0.076, test_lapse 1, test lapse prop. 0.011
[84] 1
Fold 54, train count 12501, test count 71, train_lapse 946, train lapse prop. 0.076, test_lapse 3, test lapse prop. 0.042
[85] 1
Fold 55, train count 12482, test count 90, train_lapse 912, train lapse prop. 0.073, test_lapse 37, test lapse prop. 0.411
[86] 1
Fold 56, train count 12482, test count 90, train_lapse 949, train lapse prop. 0.076, test_lapse 0, test lapse prop. 0.000
[88] 1
Fold 57, train count 12514, test count 58, train_lapse 948, train lapse prop. 0.076, test_lapse 1, test lapse prop. 0.017
[90] 1
Fold 58, train count 12485, test count 87, train_lapse 942, train lapse prop. 0.075, test_lapse 7, test lapse prop. 0.080
[92] 1
Fold 59, train count 12550, test count 22, train_lapse 943, train lapse prop. 0.075, test_lapse 6, test lapse prop. 0.273
[93] 1
Fold 60, train count 12482, test count 90, train_lapse 949, train lapse prop. 0.076, test_lapse 0, test lapse prop. 0.000
[94] 1
Fold 61, train count 12483, test count 89, train_lapse 948, train lapse prop. 0.076, test_lapse 1, test lapse prop. 0.011
[97] 1
Fold 62, train count 12482, test count 90, train_lapse 910, train lapse prop. 0.073, test_lapse 39, test lapse prop. 0.433
[98] 1
Fold 63, train count 12482, test count 90, train_lapse 949, train lapse prop. 0.076, test_lapse 0, test lapse prop. 0.000
[99] 1
Fold 64, train count 12482, test count 90, train_lapse 947, train lapse prop. 0.076, test_lapse 2, test lapse prop. 0.022
[100] 1
Fold 65, train count 12482, test count 90, train_lapse 949, train lapse prop. 0.076, test_lapse 0, test lapse prop. 0.000
[103] 1
Fold 66, train count 12482, test count 90, train_lapse 935, train lapse prop. 0.075, test_lapse 14, test lapse prop. 0.156
[109] 1
Fold 67, train count 12482, test count 90, train_lapse 947, train lapse prop. 0.076, test_lapse 2, test lapse prop. 0.022
[110] 1
Fold 68, train count 12514, test count 58, train_lapse 940, train lapse prop. 0.075, test_lapse 9, test lapse prop. 0.155
[116] 1
Fold 69, train count 12482, test count 90, train_lapse 939, train lapse prop. 0.075, test_lapse 10, test lapse prop. 0.111
[117] 1
Fold 70, train count 12482, test count 90, train_lapse 940, train lapse prop. 0.075, test_lapse 9, test lapse prop. 0.100
[118] 1
Fold 71, train count 12482, test count 90, train_lapse 948, train lapse prop. 0.076, test_lapse 1, test lapse prop. 0.011
[119] 1
Fold 72, train count 12482, test count 90, train_lapse 922, train lapse prop. 0.074, test_lapse 27, test lapse prop. 0.300
[121] 1
Fold 73, train count 12482, test count 90, train_lapse 895, train lapse prop. 0.072, test_lapse 54, test lapse prop. 0.600
[128] 1
Fold 74, train count 12482, test count 90, train_lapse 949, train lapse prop. 0.076, test_lapse 0, test lapse prop. 0.000
[130] 1
Fold 75, train count 12482, test count 90, train_lapse 922, train lapse prop. 0.074, test_lapse 27, test lapse prop. 0.300
[131] 1
Fold 76, train count 12483, test count 89, train_lapse 949, train lapse prop. 0.076, test_lapse 0, test lapse prop. 0.000
[134] 1
Fold 77, train count 12482, test count 90, train_lapse 949, train lapse prop. 0.076, test_lapse 0, test lapse prop. 0.000
[135] 1
Fold 78, train count 12482, test count 90, train_lapse 949, train lapse prop. 0.076, test_lapse 0, test lapse prop. 0.000
[136] 1
Fold 79, train count 12482, test count 90, train_lapse 931, train lapse prop. 0.075, test_lapse 18, test lapse prop. 0.200
[137] 1
Fold 80, train count 12482, test count 90, train_lapse 949, train lapse prop. 0.076, test_lapse 0, test lapse prop. 0.000
[138] 1
Fold 81, train count 12483, test count 89, train_lapse 949, train lapse prop. 0.076, test_lapse 0, test lapse prop. 0.000
[139] 1
Fold 82, train count 12483, test count 89, train_lapse 949, train lapse prop. 0.076, test_lapse 0, test lapse prop. 0.000
[143] 1
Fold 83, train count 12496, test count 76, train_lapse 948, train lapse prop. 0.076, test_lapse 1, test lapse prop. 0.013
[149] 1
Fold 84, train count 12483, test count 89, train_lapse 944, train lapse prop. 0.076, test_lapse 5, test lapse prop. 0.056
[150] 1
Fold 85, train count 12482, test count 90, train_lapse 949, train lapse prop. 0.076, test_lapse 0, test lapse prop. 0.000
[156] 1
Fold 86, train count 12482, test count 90, train_lapse 946, train lapse prop. 0.076, test_lapse 3, test lapse prop. 0.033
[158] 1
Fold 87, train count 12482, test count 90, train_lapse 948, train lapse prop. 0.076, test_lapse 1, test lapse prop. 0.011
[161] 1
Fold 88, train count 12482, test count 90, train_lapse 949, train lapse prop. 0.076, test_lapse 0, test lapse prop. 0.000
[162] 1
Fold 89, train count 12482, test count 90, train_lapse 949, train lapse prop. 0.076, test_lapse 0, test lapse prop. 0.000
[163] 1
Fold 90, train count 12485, test count 87, train_lapse 931, train lapse prop. 0.075, test_lapse 18, test lapse prop. 0.207
[166] 1
Fold 91, train count 12485, test count 87, train_lapse 949, train lapse prop. 0.076, test_lapse 0, test lapse prop. 0.000
[167] 1
Fold 92, train count 12482, test count 90, train_lapse 939, train lapse prop. 0.075, test_lapse 10, test lapse prop. 0.111
[169] 1
Fold 93, train count 12482, test count 90, train_lapse 949, train lapse prop. 0.076, test_lapse 0, test lapse prop. 0.000
[171] 1
Fold 94, train count 12538, test count 34, train_lapse 946, train lapse prop. 0.075, test_lapse 3, test lapse prop. 0.088
[172] 1
Fold 95, train count 12483, test count 89, train_lapse 944, train lapse prop. 0.076, test_lapse 5, test lapse prop. 0.056
[175] 1
Fold 96, train count 12484, test count 88, train_lapse 943, train lapse prop. 0.076, test_lapse 6, test lapse prop. 0.068
[178] 1
Fold 97, train count 12483, test count 89, train_lapse 949, train lapse prop. 0.076, test_lapse 0, test lapse prop. 0.000
[179] 1
Fold 98, train count 12483, test count 89, train_lapse 929, train lapse prop. 0.074, test_lapse 20, test lapse prop. 0.225
[180] 1
Fold 99, train count 12482, test count 90, train_lapse 949, train lapse prop. 0.076, test_lapse 0, test lapse prop. 0.000
[181] 1
Fold 100, train count 12484, test count 88, train_lapse 949, train lapse prop. 0.076, test_lapse 0, test lapse prop. 0.000
[183] 1
Fold 101, train count 12483, test count 89, train_lapse 947, train lapse prop. 0.076, test_lapse 2, test lapse prop. 0.022
[185] 1
Fold 102, train count 12482, test count 90, train_lapse 949, train lapse prop. 0.076, test_lapse 0, test lapse prop. 0.000
[187] 1
Fold 103, train count 12482, test count 90, train_lapse 949, train lapse prop. 0.076, test_lapse 0, test lapse prop. 0.000
[188] 1
Fold 104, train count 12482, test count 90, train_lapse 942, train lapse prop. 0.075, test_lapse 7, test lapse prop. 0.078
[189] 1
Fold 105, train count 12483, test count 89, train_lapse 949, train lapse prop. 0.076, test_lapse 0, test lapse prop. 0.000
[190] 1
Fold 106, train count 12485, test count 87, train_lapse 937, train lapse prop. 0.075, test_lapse 12, test lapse prop. 0.138
[191] 1
Fold 107, train count 12482, test count 90, train_lapse 949, train lapse prop. 0.076, test_lapse 0, test lapse prop. 0.000
[192] 1
Fold 108, train count 12484, test count 88, train_lapse 949, train lapse prop. 0.076, test_lapse 0, test lapse prop. 0.000
[196] 1
Fold 109, train count 12482, test count 90, train_lapse 949, train lapse prop. 0.076, test_lapse 0, test lapse prop. 0.000
[197] 1
Fold 110, train count 12530, test count 42, train_lapse 949, train lapse prop. 0.076, test_lapse 0, test lapse prop. 0.000
[200] 1
Fold 111, train count 12483, test count 89, train_lapse 949, train lapse prop. 0.076, test_lapse 0, test lapse prop. 0.000
[201] 1
Fold 112, train count 12482, test count 90, train_lapse 949, train lapse prop. 0.076, test_lapse 0, test lapse prop. 0.000
[203] 1
Fold 113, train count 12493, test count 79, train_lapse 949, train lapse prop. 0.076, test_lapse 0, test lapse prop. 0.000
[205] 1
Fold 114, train count 12482, test count 90, train_lapse 944, train lapse prop. 0.076, test_lapse 5, test lapse prop. 0.056
[207] 1
Fold 115, train count 12482, test count 90, train_lapse 949, train lapse prop. 0.076, test_lapse 0, test lapse prop. 0.000
[208] 1
Fold 116, train count 12515, test count 57, train_lapse 949, train lapse prop. 0.076, test_lapse 0, test lapse prop. 0.000
[209] 1
Fold 117, train count 12482, test count 90, train_lapse 926, train lapse prop. 0.074, test_lapse 23, test lapse prop. 0.256
[211] 1
Fold 118, train count 12515, test count 57, train_lapse 940, train lapse prop. 0.075, test_lapse 9, test lapse prop. 0.158
[212] 1
Fold 119, train count 12482, test count 90, train_lapse 936, train lapse prop. 0.075, test_lapse 13, test lapse prop. 0.144
[213] 1
Fold 120, train count 12482, test count 90, train_lapse 930, train lapse prop. 0.075, test_lapse 19, test lapse prop. 0.211
[214] 1
Fold 121, train count 12482, test count 90, train_lapse 949, train lapse prop. 0.076, test_lapse 0, test lapse prop. 0.000
[215] 1
Fold 122, train count 12514, test count 58, train_lapse 934, train lapse prop. 0.075, test_lapse 15, test lapse prop. 0.259
[218] 1
Fold 123, train count 12518, test count 54, train_lapse 938, train lapse prop. 0.075, test_lapse 11, test lapse prop. 0.204
[221] 1
Fold 124, train count 12482, test count 90, train_lapse 949, train lapse prop. 0.076, test_lapse 0, test lapse prop. 0.000
[222] 1
Fold 125, train count 12482, test count 90, train_lapse 949, train lapse prop. 0.076, test_lapse 0, test lapse prop. 0.000
[223] 1
Fold 126, train count 12482, test count 90, train_lapse 949, train lapse prop. 0.076, test_lapse 0, test lapse prop. 0.000
[224] 1
Fold 127, train count 12482, test count 90, train_lapse 948, train lapse prop. 0.076, test_lapse 1, test lapse prop. 0.011
[225] 1
Fold 128, train count 12482, test count 90, train_lapse 948, train lapse prop. 0.076, test_lapse 1, test lapse prop. 0.011
[230] 1
Fold 129, train count 12490, test count 82, train_lapse 946, train lapse prop. 0.076, test_lapse 3, test lapse prop. 0.037
[231] 1
Fold 130, train count 12482, test count 90, train_lapse 934, train lapse prop. 0.075, test_lapse 15, test lapse prop. 0.167
[234] 1
Fold 131, train count 12482, test count 90, train_lapse 944, train lapse prop. 0.076, test_lapse 5, test lapse prop. 0.056
[236] 1
Fold 132, train count 12482, test count 90, train_lapse 949, train lapse prop. 0.076, test_lapse 0, test lapse prop. 0.000
[238] 1
Fold 133, train count 12482, test count 90, train_lapse 949, train lapse prop. 0.076, test_lapse 0, test lapse prop. 0.000
[240] 1
Fold 134, train count 12482, test count 90, train_lapse 931, train lapse prop. 0.075, test_lapse 18, test lapse prop. 0.200
[241] 1
Fold 135, train count 12482, test count 90, train_lapse 949, train lapse prop. 0.076, test_lapse 0, test lapse prop. 0.000
[242] 1
Fold 136, train count 12493, test count 79, train_lapse 949, train lapse prop. 0.076, test_lapse 0, test lapse prop. 0.000
[243] 1
Fold 137, train count 12485, test count 87, train_lapse 949, train lapse prop. 0.076, test_lapse 0, test lapse prop. 0.000
[245] 1
Fold 138, train count 12482, test count 90, train_lapse 949, train lapse prop. 0.076, test_lapse 0, test lapse prop. 0.000
[248] 1
Fold 139, train count 12482, test count 90, train_lapse 949, train lapse prop. 0.076, test_lapse 0, test lapse prop. 0.000
[252] 1
Fold 140, train count 12482, test count 90, train_lapse 949, train lapse prop. 0.076, test_lapse 0, test lapse prop. 0.000
[255] 1
Fold 141, train count 12482, test count 90, train_lapse 949, train lapse prop. 0.076, test_lapse 0, test lapse prop. 0.000
[259] 1
Fold 142, train count 12482, test count 90, train_lapse 949, train lapse prop. 0.076, test_lapse 0, test lapse prop. 0.000
[262] 1
Fold 143, train count 12487, test count 85, train_lapse 942, train lapse prop. 0.075, test_lapse 7, test lapse prop. 0.082
[263] 1
Fold 144, train count 12482, test count 90, train_lapse 949, train lapse prop. 0.076, test_lapse 0, test lapse prop. 0.000
[264] 1
Fold 145, train count 12496, test count 76, train_lapse 948, train lapse prop. 0.076, test_lapse 1, test lapse prop. 0.013
[265] 1
Fold 146, train count 12482, test count 90, train_lapse 931, train lapse prop. 0.075, test_lapse 18, test lapse prop. 0.200
[268] 1
Fold 147, train count 12482, test count 90, train_lapse 948, train lapse prop. 0.076, test_lapse 1, test lapse prop. 0.011
[270] 1
{
    "splitLOO0_rsLOO0_foldLOO0_id1": {
        "train": [
            2,
            3,
            5,
            6,
            7,
            9,
            10,
            11,
            15,
            16,
            18,
            19,
            20,
            21,
            23,
            25,
            26,
            27,
            28,
            29,
            30,
            31,
            32,
            33,
            34,
            37,
            38,
            39,
            40,
            42,
            43,
            44,
            47,
            48,
            51,
            52,
            53,
            54,
            56,
            58,
            59,
            63,
            64,
            65,